name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "17 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    name: Generate GitHub Analytics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}

        with:
          USERNAME: yassinekamouss
          BRANCH_NAME: main
          UTC_OFFSET: 1
          EXCLUDE: ""
          AUTO_PUSH: true
          THEME: github_dark
          ANIMATION: none
          DURATION: ""
          NAME: "Yassine Kamouss"
